---
# tasks file for user-gestion

- name: Add users and groups
  include_tasks: manage_user.yml
  loop: "{{ manage_users|d([]) }}"
  loop_control:
    loop_var: manage_user
  when: manage_users|d(False)